### ISSUE TITLE
Add array splitting to query param validation

### ISSUE THREAD

**Issue by maroux** [pipermerriam/flex#114]
For a parameter declaration like so:
```
  user_id__in:
    name: user_id__in
    in: query
    type: array
    items:
      type: string
    collectionFormat: csv
```

Flex should be able to validate the query param: `user_id__in=b75125a456387da15b964122,bb0a9dfd9a9401429b71ad4d,259f6471b2b2f1793c4aa2cf` by splitting it into an array based on the type declaration. Thoughts?
