### ISSUE TITLE
load fails on a schema that has a parameter of type `file`

### ISSUE THREAD

**Issue by maroux** [pipermerriam/flex#122]
Example:

```
  /media/:
    post:
      summary: Upload media
      operationId: operation
      description: upload a file and reference it using a url.
      consumes: [ multipart/form-data ]
      parameters:
        - name: photo
          in: formData
          description: Photo to upload
          required: true
          type: file
```
