### ISSUE TITLE
required fields

### ISSUE THREAD

**Issue by nicolastrres** [pipermerriam/flex#62]
Hi @pipermerriam, I found something that maybe we can improve. 
At this moment the required fields should be set like this:
```yaml
Pet:
    properties:
      id:
        type: integer
        required: true
        format: int64
      name:
        type: string
        required: true
```
But I saw the [swagger specification](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#simple-model) and some [examples](https://github.com/swagger-api/swagger-spec/blob/master/examples/v2.0/yaml/petstore-expanded.yaml) and they do something like this:
```yaml
Pet:
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
```

My problem with the actual solution, it's that when we use our swagger files with other tools for example [swagger editor](http://editor.swagger.io/), it doesn't work. 

What do you think about this @pipermerriam ?

**Comment by pipermerriam** [comment]
Facinating.  It looks like the current implementation of the `required` field is utterly wrong.

[json schema required spec](http://json-schema.org/latest/json-schema-validation.html#anchor61)

> The value of this keyword MUST be an array. This array MUST have at least one element. Elements of this array MUST be strings, and MUST be unique.

It looks like this yaml is actually *invalid* in that the required keyword is being mis-used.

```yaml
Pet:
    properties:
      id:
        type: integer
        required: true
        format: int64
```

I'm going to consider this a bug that needs to be fixed.
