### ISSUE TITLE
Allow nullable values

### ISSUE THREAD

**Issue by LucasRoesler** [pipermerriam/flex#91]
I would like to add a way to validate nullable values.  I thought that the format validation might allow me to do this, but it is separate from the type validation.   I don't mind submitting the code, but I would love a pointer on where to start.  

The biggest potential issue is that swagger does not officially define nullable fields. In fact, `null` isn't allowed in the spec. So either a spec would need to be picked or it would need to be configurable. We have been using `x-nullable: true` in our specs.   For example,

```yaml
properties:
  id:
    type: integer
    format: int32
  organization_id:
    type: integer
    format: int32
  email:
    type: string
  first_name:
    type: string
    x-nullable: true
```

As per https://github.com/swagger-api/swagger-spec/issues/229, `x-nullable` and `x-isnullable` seem to be popular choices for people with nullable fields.

**Comment by pipermerriam** [comment]
You should be able to do the following.

```
properties:
  id:
    type: [integer, null]
    format: int32
  organization_id:
    type: [integer, null]
    format: int32
  email:
    type: [string, null]
  first_name:
    type: [string, null]
```

The `type` field in json-schema allows for either a string, or an array of strings.

http://json-schema.org/latest/json-schema-validation.html#anchor79

Feel free to re-open if this doesn't solve your problem.
